project:
  type: website

preview: 
  port: 5555
  browser: true
  watch-inputs: true
  navigate: true

website:
  bread-crumbs: false
  page-footer: 
    center:
      - text: "{{< iconify simple-icons:gmail>}}"
        href: mailto:tajacinto@gmail.com
      - text: "{{< iconify simple-icons:linkedin>}}"
        href: https://www.linkedin.com/in/tiagojac/
      - text: "{{< iconify simple-icons:github>}}"
        href: https://www.github.com/taqjac/
      - text: "{{< iconify simple-icons:researchgate>}}"
        href: https://www.researchgate.net/profile/Tiago-Jacinto
      - text: "{{< iconify simple-icons:orcid>}}"
        href: https://orcid.org/0000-0002-7897-1101
      - text: "{{< iconify simple-icons:instagram>}}"
        href: https://instagram.com/taqjac
      - text: "{{< iconify simple-icons:lastdotfm>}}"
        href: https://www.last.fm/user/taqjac
      - text: "{{< iconify simple-icons:letterboxd>}}"
        href: https://letterboxd.com/taqjac/
      - text: "{{< iconify simple-icons:bluesky>}}"
        href: https://bsky.app/profile/taqjac.bsky.social
      - text: "{{< iconify simple-icons:mastodon>}}"
        href: https://indieweb.social/@taqjac
      - text: "{{< iconify simple-icons:x>}}"
        href: https://twitter.com/taqjac
      
format:
  html:
    theme: zephyr



  
