project:
  type: website
  output-dir: docs

website:
  title: "Tiago Jacinto"
  navbar:
    background: dark
    
    left:
      - about.qmd
      - posts.qmd
      - uses/index.qmd
      
body-footer: | 
  This page brought to you by <https://example.com>  

format:
  html:
    pagetitle: "{{< meta title >}} | Tiago Jacinto"
    theme: 
      light: [custom.scss, cosmo ]
      dark:  [custom.scss, darkly]
    
    grid:
      body-width: 800px
    anchor-sections: true
    link-external-icon: false
    link-external-newwindow: true
    footnotes-hover: true
    toc: true
    page-layout: full

editor: visual

