project:
  type: website
  output-dir: docs

website:
  title: "TJ.EU"
  site-url: https://www.tiagojacinto.eu
  description: "A personal website"
  site-url: http://tiagojacinto.eu
  navbar:
    background: primary
    pinned: true
    
    left:
      - about/index.qmd
      # - notes/index.qmd
      - uses/index.qmd

    right:
      - text: "{{< fa brands linkedin-in title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/tiagojacinto
        rel: me
      - text: "{{< fa brands github title='Github' >}}"
        href: https://github.com/taqjac
        rel: me
      - icon: rss
        href: index.xml
      
  page-footer:
    left: |
      {{< fa brands creative-commons >}} {{< var years >}} Tiago Jacinto <br>
      All content [{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
    center: |
      
    right: |
      Made with [VSCodium](https://vscodium.com/) and [Quarto](https://quarto.org/) | [Source {{< fa brands github >}}]({{< var github-url >}})

format:
  html:
    pagetitle: "{{< meta title >}} | Tiago Jacinto"
    theme: [custom.scss, cosmo]
    anchor-sections: true
    link-external-icon: false
    link-external-newwindow: true
    footnotes-hover: true
    toc: true
    

bibliography: references.bib
csl: chicago-author-date.csl

editor: visual

