project:
  type: website

preview: 
  port: 5555
  browser: true
  watch-inputs: true
  navigate: true

website:
  bread-crumbs: false
  google-analytics: G-326RT0TBNM
  page-footer: 
    center:
      Made with {{< iconify simple-icons:quarto>}} and {{< iconify zondicons:coffee>}}
      
format:
  html:
    theme: zephyr



  
